### ISSUE TITLE
Generated RSS feed is invalid

### ISSUE THREAD

**Issue by sockeqwe** [TheContext/podcaster#19]
Just for fun I generated a RSS Feed with all of our 20 episodes and checked the generated output with some online tools.

Unfortunately, the generated rss feed doesn't seem to be valid:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fraw.githubusercontent.com%2Fartem-zinnatullin%2FTheContext-Podcast%2Fyaml%2Fgenerated%2Fpodcast.rss

http://castfeedvalidator.com/?url=https://raw.githubusercontent.com/artem-zinnatullin/TheContext-Podcast/yaml/generated/podcast.rss

**Comment by ming13** [comment]
Yep, it is not finished, at least from the compatibility perspective.

BTW, we probably should drop `<atom:contributor>` and `<atom:author>`. I haven’t saw popular feeds with these tags and they are not used by podcast players at all.

**Comment by ming13** [comment]
The current feed looks good at validators, please reopen if not so.
